"""remove pharmapi_api_key from pharmacist_pharmacies

Revision ID: 077777e70a09
Revises: a6dca15199eb
Create Date: 2026-05-17 00:42:36.669607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077777e70a09'
down_revision: Union[str, Sequence[str], None] = 'a6dca15199eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacist_pharmacies', 'pharmapi_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacist_pharmacies', sa.Column('pharmapi_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###
