"""add spc documents, fetch state, sync runs, drug_catalog eof_code

Revision ID: 31fd353d3ccc
Revises: 354c768c69a7
Create Date: 2026-07-17 04:15:20.847736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31fd353d3ccc'
down_revision: Union[str, Sequence[str], None] = '354c768c69a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spc_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('atc_code', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=2), server_default=sa.text("'el'"), nullable=False),
    sa.Column('raw_pdf', sa.LargeBinary(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_method', sa.String(length=16), server_default=sa.text("'deterministic'"), nullable=False),
    sa.Column('parse_status', sa.String(length=10), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spc_documents'))
    )
    op.create_index('ix_spc_documents_atc_code', 'spc_documents', ['atc_code'], unique=False)
    op.create_index('ix_spc_documents_barcode', 'spc_documents', ['barcode'], unique=False)
    op.create_table('spc_fetch_state',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spc_fetch_state')),
    sa.UniqueConstraint('barcode', 'source', name=op.f('uq_spc_fetch_state_barcode'))
    )
    op.create_index('ix_spc_fetch_state_next_attempt', 'spc_fetch_state', ['next_attempt_at'], unique=False)
    op.create_table('spc_sync_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'running'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('examined', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fetched_docs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parsed_docs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spc_sync_runs'))
    )
    op.add_column('drug_catalog', sa.Column('eof_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_drug_catalog_eof_code'), 'drug_catalog', ['eof_code'], unique=False)
    # updated_at triggers — repo convention (463cc54e7949).
    for table in ("spc_documents", "spc_fetch_state", "spc_sync_runs"):
        op.execute(
            f"CREATE TRIGGER trg_{table}_set_updated_at "
            f"BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION set_updated_at_now();"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ("spc_documents", "spc_fetch_state", "spc_sync_runs"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_set_updated_at ON {table};")
    op.drop_index(op.f('ix_drug_catalog_eof_code'), table_name='drug_catalog')
    op.drop_column('drug_catalog', 'eof_code')
    op.drop_table('spc_sync_runs')
    op.drop_index('ix_spc_fetch_state_next_attempt', table_name='spc_fetch_state')
    op.drop_table('spc_fetch_state')
    op.drop_index('ix_spc_documents_barcode', table_name='spc_documents')
    op.drop_index('ix_spc_documents_atc_code', table_name='spc_documents')
    op.drop_table('spc_documents')
    # ### end Alembic commands ###
