"""add patients registry

Revision ID: 354c768c69a7
Revises: d048274bbe99
Create Date: 2026-07-17 01:10:31.883884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '354c768c69a7'
down_revision: Union[str, Sequence[str], None] = 'd048274bbe99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('amka', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_patients_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('pharmacy_id', 'amka', name=op.f('uq_patients_pharmacy_id'))
    )
    op.create_index('ix_patients_pharmacy_last_seen', 'patients', ['pharmacy_id', 'last_seen_at'], unique=False)
    # updated_at trigger — repo convention (463cc54e7949).
    op.execute(
        "CREATE TRIGGER trg_patients_set_updated_at "
        "BEFORE UPDATE ON patients "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at_now();"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_patients_set_updated_at ON patients;")
    op.drop_index('ix_patients_pharmacy_last_seen', table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
