"""add_drug_catalog_and_safety_rules

Revision ID: 5f7d13af4299
Revises: 3f8a2b1c9d4e
Create Date: 2026-05-13 18:32:23.235583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7d13af4299'
down_revision: Union[str, Sequence[str], None] = '3f8a2b1c9d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_catalog',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('gns_code', sa.String(), nullable=False),
    sa.Column('atc_code', sa.String(), nullable=False),
    sa.Column('atc_class', sa.String(), nullable=False),
    sa.Column('name_gr', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('interaction_group', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drug_catalog')),
    sa.UniqueConstraint('gns_code', name=op.f('uq_drug_catalog_gns_code'))
    )
    op.create_table('safety_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('check_type', sa.String(), nullable=False),
    sa.Column('trigger_atc', sa.String(), nullable=True),
    sa.Column('trigger_condition_code', sa.String(), nullable=True),
    sa.Column('conflicting_atc', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message_en', sa.String(), nullable=False),
    sa.Column('details_en', sa.Text(), nullable=True),
    sa.Column('recommended_action_en', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_rules')),
    sa.UniqueConstraint('rule_code', name=op.f('uq_safety_rules_rule_code'))
    )
    for table in ("drug_catalog", "safety_rules"):
        op.execute(
            f"CREATE TRIGGER trg_{table}_set_updated_at "
            f"BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at_now();"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safety_rules')
    op.drop_table('drug_catalog')
    # ### end Alembic commands ###
