"""initial_schema

Revision ID: 73eaa75afe13
Revises: 
Create Date: 2026-05-08 03:47:44.372223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73eaa75afe13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('pharmapi_unit_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pharmacies'))
    )
    op.create_table('pharmacists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('eof_licence_no', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pharmacists')),
    sa.UniqueConstraint('email', name=op.f('uq_pharmacists_email')),
    sa.UniqueConstraint('eof_licence_no', name=op.f('uq_pharmacists_eof_licence_no'))
    )
    op.create_table('adr_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pharmacist_id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('patient_amka', sa.String(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('medicine_barcode', sa.String(), nullable=True),
    sa.Column('medicine_name', sa.String(), nullable=True),
    sa.Column('atc_code', sa.String(), nullable=True),
    sa.Column('symptom_description', sa.String(), nullable=False),
    sa.Column('onset_timing', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('eof_report_ref', sa.String(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['pharmacists.id'], name=op.f('fk_adr_reports_pharmacist_id_pharmacists')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_adr_reports_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adr_reports'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pharmacist_id', sa.UUID(), nullable=True),
    sa.Column('pharmacy_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('pharmapi_path', sa.String(), nullable=True),
    sa.Column('pharmapi_status', sa.Integer(), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_code', sa.String(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['pharmacists.id'], name=op.f('fk_audit_log_pharmacist_id_pharmacists')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_audit_log_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('documentation_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pharmacist_id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('prescription_barcode', sa.String(), nullable=False),
    sa.Column('patient_amka', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('medicine_barcode', sa.String(), nullable=True),
    sa.Column('medicine_name', sa.String(), nullable=False),
    sa.Column('info_provided', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('delivery_method', sa.String(), nullable=False),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pharmapi_exec_ref', sa.String(), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pharmacist_signature', sa.String(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['pharmacists.id'], name=op.f('fk_documentation_logs_pharmacist_id_pharmacists')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_documentation_logs_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentation_logs'))
    )
    op.create_index('ix_doc_logs_patient_amka_dispensed', 'documentation_logs', ['patient_amka', 'dispensed_at'], unique=False)
    op.create_index('ix_doc_logs_pharmacy_dispensed', 'documentation_logs', ['pharmacy_id', 'dispensed_at'], unique=False)
    op.create_table('patient_conditions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('amka', sa.String(), nullable=False),
    sa.Column('condition_code', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_patient_conditions_pharmacy_id_pharmacies')),
    sa.ForeignKeyConstraint(['recorded_by'], ['pharmacists.id'], name=op.f('fk_patient_conditions_recorded_by_pharmacists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_conditions'))
    )
    op.create_index('ix_patient_conditions_amka_active', 'patient_conditions', ['amka'], unique=False, postgresql_where=sa.text('active = true'))
    op.create_table('pharmacist_pharmacies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pharmacist_id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('pharmapi_username', sa.String(), nullable=True),
    sa.Column('pharmapi_password', sa.String(), nullable=True),
    sa.Column('pharmapi_api_key', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['pharmacists.id'], name=op.f('fk_pharmacist_pharmacies_pharmacist_id_pharmacists')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_pharmacist_pharmacies_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pharmacist_pharmacies')),
    sa.UniqueConstraint('pharmacist_id', 'pharmacy_id', name=op.f('uq_pharmacist_pharmacies_pharmacist_id'))
    )
    op.create_table('adr_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('adr_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['pharmacists.id'], name=op.f('fk_adr_events_actor_id_pharmacists')),
    sa.ForeignKeyConstraint(['adr_id'], ['adr_reports.id'], name=op.f('fk_adr_events_adr_id_adr_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adr_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adr_events')
    op.drop_table('pharmacist_pharmacies')
    op.drop_index('ix_patient_conditions_amka_active', table_name='patient_conditions', postgresql_where=sa.text('active = true'))
    op.drop_table('patient_conditions')
    op.drop_index('ix_doc_logs_pharmacy_dispensed', table_name='documentation_logs')
    op.drop_index('ix_doc_logs_patient_amka_dispensed', table_name='documentation_logs')
    op.drop_table('documentation_logs')
    op.drop_table('audit_log')
    op.drop_table('adr_reports')
    op.drop_table('pharmacists')
    op.drop_table('pharmacies')
    # ### end Alembic commands ###
