"""add staff_users and audit staff_id

Revision ID: 8d7b5d8f0f5c
Revises: b81649811cdb
Create Date: 2026-05-17 05:10:47.812792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7b5d8f0f5c'
down_revision: Union[str, Sequence[str], None] = 'b81649811cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default=sa.text("'admin'"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_users')),
    sa.UniqueConstraint('email', name=op.f('uq_staff_users_email'))
    )
    op.add_column('audit_log', sa.Column('staff_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_audit_log_staff_id_staff_users'), 'audit_log', 'staff_users', ['staff_id'], ['id'])
    op.add_column('invitations', sa.Column('invited_by_staff_id', sa.UUID(), nullable=True))
    op.alter_column('invitations', 'invited_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(op.f('fk_invitations_invited_by_staff_id_staff_users'), 'invitations', 'staff_users', ['invited_by_staff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_invitations_invited_by_staff_id_staff_users'), 'invitations', type_='foreignkey')
    op.alter_column('invitations', 'invited_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('invitations', 'invited_by_staff_id')
    op.drop_constraint(op.f('fk_audit_log_staff_id_staff_users'), 'audit_log', type_='foreignkey')
    op.drop_column('audit_log', 'staff_id')
    op.drop_table('staff_users')
    # ### end Alembic commands ###
