"""add dispense_logs

Revision ID: 9c23510abc0e
Revises: 5b2169e3d392
Create Date: 2026-06-09 01:42:32.548612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c23510abc0e'
down_revision: Union[str, Sequence[str], None] = '5b2169e3d392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispense_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('pharmacist_id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('exec_ref', sa.String(), nullable=False),
    sa.Column('request_cda', sa.Text(), nullable=False),
    sa.Column('response_cda', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['pharmacists.id'], name=op.f('fk_dispense_logs_pharmacist_id_pharmacists')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_dispense_logs_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispense_logs'))
    )
    op.create_index('ix_dispense_logs_pharmacy_barcode', 'dispense_logs', ['pharmacy_id', 'barcode'], unique=False)
    op.create_index('ix_dispense_logs_pharmacy_created', 'dispense_logs', ['pharmacy_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dispense_logs_pharmacy_created', table_name='dispense_logs')
    op.drop_index('ix_dispense_logs_pharmacy_barcode', table_name='dispense_logs')
    op.drop_table('dispense_logs')
    # ### end Alembic commands ###
