"""enrich pharmacies address and contact

Revision ID: a6dca15199eb
Revises: 5f7d13af4299
Create Date: 2026-05-17 00:06:36.666823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6dca15199eb'
down_revision: Union[str, Sequence[str], None] = '5f7d13af4299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacies', sa.Column('street_name', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('street_number', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('area', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('city', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('fax', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('email', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('geographic_region', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('accounting_category', sa.String(), nullable=True))
    op.add_column(
        'pharmacies',
        sa.Column('is_branch', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacies', 'is_branch')
    op.drop_column('pharmacies', 'accounting_category')
    op.drop_column('pharmacies', 'geographic_region')
    op.drop_column('pharmacies', 'email')
    op.drop_column('pharmacies', 'fax')
    op.drop_column('pharmacies', 'phone')
    op.drop_column('pharmacies', 'postal_code')
    op.drop_column('pharmacies', 'city')
    op.drop_column('pharmacies', 'area')
    op.drop_column('pharmacies', 'street_number')
    op.drop_column('pharmacies', 'street_name')
    # ### end Alembic commands ###
