"""dispense_logs idempotency unique + request_id

Revision ID: c7da2b900aef
Revises: 9c23510abc0e
Create Date: 2026-06-09 01:48:38.241105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7da2b900aef'
down_revision: Union[str, Sequence[str], None] = '9c23510abc0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispense_logs', sa.Column('request_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_dispense_logs_pharmacy_barcode'), table_name='dispense_logs')
    op.create_unique_constraint(op.f('uq_dispense_logs_pharmacy_id'), 'dispense_logs', ['pharmacy_id', 'barcode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_dispense_logs_pharmacy_id'), 'dispense_logs', type_='unique')
    op.create_index(op.f('ix_dispense_logs_pharmacy_barcode'), 'dispense_logs', ['pharmacy_id', 'barcode'], unique=False)
    op.drop_column('dispense_logs', 'request_id')
    # ### end Alembic commands ###
