"""add prescription_scans scan log

Revision ID: d048274bbe99
Revises: b3e6a90d1f27
Create Date: 2026-07-16 21:52:09.106943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd048274bbe99'
down_revision: Union[str, Sequence[str], None] = 'b3e6a90d1f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription_scans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('pharmacist_id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pharmapi_status', sa.String(), nullable=True),
    sa.Column('patient_amka', sa.String(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('rx_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('patient_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['pharmacists.id'], name=op.f('fk_prescription_scans_pharmacist_id_pharmacists')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_prescription_scans_pharmacy_id_pharmacies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescription_scans'))
    )
    op.create_index('ix_prescription_scans_barcode', 'prescription_scans', ['barcode'], unique=False)
    op.create_index('ix_prescription_scans_patient_amka', 'prescription_scans', ['patient_amka'], unique=False)
    op.create_index('ix_prescription_scans_pharmacy_created', 'prescription_scans', ['pharmacy_id', 'created_at'], unique=False)
    # updated_at trigger — repo convention (463cc54e7949): the DB owns
    # updated_at so raw-SQL updates stay fresh, not just ORM ones.
    op.execute(
        "CREATE TRIGGER trg_prescription_scans_set_updated_at "
        "BEFORE UPDATE ON prescription_scans "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at_now();"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER IF EXISTS trg_prescription_scans_set_updated_at ON prescription_scans;"
    )
    op.drop_index('ix_prescription_scans_pharmacy_created', table_name='prescription_scans')
    op.drop_index('ix_prescription_scans_patient_amka', table_name='prescription_scans')
    op.drop_index('ix_prescription_scans_barcode', table_name='prescription_scans')
    op.drop_table('prescription_scans')
    # ### end Alembic commands ###
