"""add_timestamps_to_all_tables

Revision ID: d8516c105cf2
Revises: 73eaa75afe13
Create Date: 2026-05-08 04:40:12.559293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8516c105cf2'
down_revision: Union[str, Sequence[str], None] = '73eaa75afe13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adr_events', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('adr_events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('adr_reports', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.execute("UPDATE adr_reports SET updated_at = now() WHERE updated_at IS NULL")
    op.alter_column('adr_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.add_column('audit_log', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('audit_log', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('documentation_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('documentation_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.execute("UPDATE patient_conditions SET updated_at = now() WHERE updated_at IS NULL")
    op.alter_column('patient_conditions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.add_column('pharmacies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('pharmacist_pharmacies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('pharmacists', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacists', 'updated_at')
    op.drop_column('pharmacist_pharmacies', 'updated_at')
    op.drop_column('pharmacies', 'updated_at')
    op.alter_column('patient_conditions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_column('documentation_logs', 'updated_at')
    op.drop_column('documentation_logs', 'created_at')
    op.drop_column('audit_log', 'updated_at')
    op.drop_column('audit_log', 'created_at')
    op.alter_column('adr_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_column('adr_reports', 'created_at')
    op.drop_column('adr_events', 'updated_at')
    op.drop_column('adr_events', 'created_at')
    # ### end Alembic commands ###
