"""add_b2b_adr_tables

Revision ID: ed59e1b260c0
Revises: b7d3f5a18c40
Create Date: 2026-06-12 02:51:06.043206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed59e1b260c0'
down_revision: Union[str, Sequence[str], None] = 'b7d3f5a18c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b2b_adr_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('created_via_api_key_id', sa.UUID(), nullable=True),
    sa.Column('patient_amka', sa.String(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('rx_id', sa.String(), nullable=True),
    sa.Column('medicine_barcode', sa.String(), nullable=True),
    sa.Column('medicine_name', sa.String(), nullable=True),
    sa.Column('atc_code', sa.String(), nullable=True),
    sa.Column('symptom_description', sa.String(), nullable=False),
    sa.Column('onset_timing', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('causality', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('eof_report_ref', sa.String(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_via_api_key_id'], ['api_keys.id'], name=op.f('fk_b2b_adr_reports_created_via_api_key_id_api_keys')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_b2b_adr_reports_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_b2b_adr_reports'))
    )
    op.create_index('ix_b2b_adr_reports_location_id', 'b2b_adr_reports', ['location_id'], unique=False)
    op.create_index('ix_b2b_adr_reports_patient_amka', 'b2b_adr_reports', ['patient_amka'], unique=False)
    op.create_index('ix_b2b_adr_reports_reported_at', 'b2b_adr_reports', ['reported_at'], unique=False)
    op.create_table('b2b_adr_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('adr_id', sa.UUID(), nullable=False),
    sa.Column('actor_api_key_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_api_key_id'], ['api_keys.id'], name=op.f('fk_b2b_adr_events_actor_api_key_id_api_keys')),
    sa.ForeignKeyConstraint(['adr_id'], ['b2b_adr_reports.id'], name=op.f('fk_b2b_adr_events_adr_id_b2b_adr_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_b2b_adr_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('b2b_adr_events')
    op.drop_index('ix_b2b_adr_reports_reported_at', table_name='b2b_adr_reports')
    op.drop_index('ix_b2b_adr_reports_patient_amka', table_name='b2b_adr_reports')
    op.drop_index('ix_b2b_adr_reports_location_id', table_name='b2b_adr_reports')
    op.drop_table('b2b_adr_reports')
    # ### end Alembic commands ###
